name: la_vie_hackathon_project
description: A new Flutter project.


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  url_launcher: ^6.1.5
  image_picker: ^0.8.5+3
  dio: ^4.0.6
  flutter_bloc: ^8.0.1
  bloc: ^8.0.3
  shared_preferences: ^2.0.15
  hexcolor: ^2.0.7
  qr_code_scanner: ^1.0.1
  curved_navigation_bar: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^2.1.6


flutter_native_splash:
  image: "assets/images/play_store_512.png"
  background_image: "assets/images/la_vie_icon_adaptive_back.png"




flutter_icons:
  image_path: "assets/images/play_store_512.png"
  android: true
  ios: true
  remove_alpha_ios: true


flutter:


  uses-material-design: true


  assets:
    - assets/images/




  fonts:
    - family: IconBroken
      fonts:
        - asset: assets/icons/icons.ttf
